### ISSUE TITLE
安卓UserAgent怎么填写？

### ISSUE THREAD

**Issue by DoveBoy** [Zero-S1/xmly_speed#1]
安卓使用httpcanary抓取喜马拉雅极速版的cookie后，不管怎么填写，运行一直报错，怀疑和代码24行有关，需要修改UserAgent，具体怎么修改？
![image](https://user-images.githubusercontent.com/19201447/94356923-9350c200-00c6-11eb-9f92-e8430e48ebfd.png)

**Comment by Zero-S1** [comment]
https://github.com/Zero-S1/xmly_speed/blob/096442328ca129516729ef6403efdc7c00999d8b/xmly_speed.py#L31

**Comment by Zero-S1** [comment]
> 安卓使用httpcanary抓取喜马拉雅极速版的cookie后，不管怎么填写，运行一直报错，怀疑和代码24行有关，需要修改UserAgent，具体怎么修改？

可能不是这个原因  去app玩一会看看

**Comment by DoveBoy** [comment]
> > 安卓使用httpcanary抓取喜马拉雅极速版的cookie后，不管怎么填写，运行一直报错，怀疑和代码24行有关，需要修改UserAgent，具体怎么修改？
> 
> 可能不是这个原因 去app玩一会看看

实测，更改user-agent后无效，依旧报错
![image](https://user-images.githubusercontent.com/19201447/94357769-3e18ae80-00ce-11eb-9ac6-1a28c6ea9751.png)

**Comment by Zero-S1** [comment]
> > > 安卓使用httpcanary抓取喜马拉雅极速版的cookie后，不管怎么填写，运行一直报错，怀疑和代码24行有关，需要修改UserAgent，具体怎么修改？
> > 
> > 
> > 可能不是这个原因 去app玩一会看看
> 
> 实测，更改user-agent后无效，依旧报错
> ![image](https://user-images.githubusercontent.com/19201447/94357769-3e18ae80-00ce-11eb-9ac6-1a28c6ea9751.png)

你账号玩不了猜拳？

**Comment by DoveBoy** [comment]
> > > > 安卓使用httpcanary抓取喜马拉雅极速版的cookie后，不管怎么填写，运行一直报错，怀疑和代码24行有关，需要修改UserAgent，具体怎么修改？
> > > 
> > > 
> > > 可能不是这个原因 去app玩一会看看
> > 
> > 
> > 实测，更改user-agent后无效，依旧报错
> > ![image](https://user-images.githubusercontent.com/19201447/94357769-3e18ae80-00ce-11eb-9ac6-1a28c6ea9751.png)
> 
> 你账号玩不了猜拳？

试了，手动进app可以猜拳

**Comment by Zero-S1** [comment]
更新下 ，看看返回值是什么

**Comment by DoveBoy** [comment]
> 更新下 ，看看返回值是什么


![Screenshot_20200927-150836](https://user-images.githubusercontent.com/19201447/94358417-71117100-00d3-11eb-9986-28ec7c379f04.jpg)

**Comment by Zero-S1** [comment]
账号差异吧，可能需要实际上手几天   不打算修复类似的错误了  直接忽略掉

**Comment by DoveBoy** [comment]
> 账号差异吧，可能需要实际上手几天 不打算修复类似的错误了 直接忽略掉

问题找到了，不是user-agent原因，第一次需要进app手动玩一次猜拳，之后用脚本就可以了，不会报错了

**Comment by Zero-S1** [comment]
> > > > > 安卓使用httpcanary抓取喜马拉雅极速版的cookie后，不管怎么填写，运行一直报错，怀疑和代码24行有关，需要修改UserAgent，具体怎么修改？
> > > > 
> > > > 
> > > > 可能不是这个原因 去app玩一会看看
> > > 
> > > 
> > > 实测，更改user-agent后无效，依旧报错
> > > ![image](https://user-images.githubusercontent.com/19201447/94357769-3e18ae80-00ce-11eb-9ac6-1a28c6ea9751.png)
> > 
> > 
> > 你账号玩不了猜拳？
> 
> 试了，手动进app可以猜拳

不是吧 进入了都不带点击试试
