### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dz515704201** [Zero-S1/xmly_speed#110]
## 1. 关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种运行方案

- [ ] 方法一：GitHub action自动运行 
- [x ] 方法二：本地运行

### (1) 具体问题
A：我是通过https://github.com/iouAkira/someDockerfile/blob/master/pack_some_script/Readme.md这个集合docker在本地运行。总共有跑了两个docke，推送设置有填写微信和TG，两个填写的推送都是一样。可以保证填写无误，现在的问题是docke1推送正常，docker2无推送。
我设定的推送时间是12点

### (2) 详细日志(如果是GitHub action运行，请附上具体网址)
这是12点附近的日志，搜索全部日志也没查找到serverJ服务启动和Telegram 推送开始
A：Jan 13 11:36:15 今日已满
Jan 13 11:36:15 
Jan 13 11:36:15 【抽卡】
Jan 13 11:36:15 抽卡机会:  [649565]
Jan 13 11:36:15 检查手牌，卡牌兑金币
Jan 13 12:02:32 执行自GitHub action
Jan 13 12:02:32 serverJ 推送打开
Jan 13 12:02:32 Telegram 推送打开
Jan 13 12:02:32 喜马拉雅极速版 (https://github.com/Zero-S1/xmly_speed/blob/master/xmly_speed.md ) ,欢迎打赏¯\(°_o)/¯
Jan 13 12:02:32 
Jan 13 12:02:32 当前时间戳: 1610510435
Jan 13 12:02:32 北京时间: 2021-01-13 12:00:35.384605

**Comment by Zero-S1** [comment]
不好意思，本人不熟悉docker，你可以求助对应的项目。

**Comment by dz515704201** [comment]
我也在找可能的原因。请问有没有这种可能，譬如我在10:40设置11:00进行通知，排除填错通知KEY的问题。会不会因为第一轮还没运转完毕就无法进行推送，或者因运行时间过短而有无法进行通知的情况？今天12点没通知后，我将推送通知改到了21点，21:18收到了推送。
