### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by xiaolaba123** [Zero-S1/xmly_speed#111]
## 1. 关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种运行方案

- [ ] 方法一：GitHub action自动运行 
- [x] 方法二：本地运行

### (1) 具体问题
A：

### (2) 详细日志(如果是GitHub action运行，请附上具体网址)
A：

**Comment by xiaolaba123** [comment]
Linux python3 运行语法报错
  File "/root/xmly/xmly_speed.py", line 97
    print(f"\n\u5f53\u524d\u65f6\u95f4\u6233: {mins}")
                           ^
SyntaxError: invalid syntax

**Comment by Zero-S1** [comment]
python3.6往上

**Comment by xiaolaba123** [comment]
换成3.9.1好了，之前3.7
