### ISSUE TITLE
[BUG]请教大佬,这个脚本,抓的安卓的cookie,放上去完全不跑金币,但是运行明显是正常的,action都是正常的,分钟数也能同步

### ISSUE THREAD

**Issue by ywk1000** [Zero-S1/xmly_speed#127]
## 1. 关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种运行方案

- [x] 方法一：GitHub action自动运行 
- [ ] 方法二：本地运行

### (1) 具体问题
A：请教大佬,这个脚本,抓的安卓的cookie,放上去完全不跑金币,但是运行明显是正常的,action都是正常的,分钟数也能同步

### (2) 详细日志(如果是GitHub action运行，请附上具体网址)
A：https://github.com/y8717/xmly_speed-07225103-72837573/actions

**Comment by ilaotan** [comment]
请使用旧版1.x版本极速版抓包.
