### ISSUE TITLE
集卡好像有大变动

### ISSUE THREAD

**Issue by MisterGlasses** [Zero-S1/xmly_speed#14]
每天可以累积30次抽奖机会，但并不会自动抽奖，需要手动，望支持一下。
![D625AA47-9DD2-4091-9735-795A5AE39087](https://user-images.githubusercontent.com/27768847/96337825-74898e00-10bc-11eb-948a-2fe07acc93cc.png)

**Comment by Zero-S1** [comment]
还没观察出规律，一张一张抽和5连抽有啥区别？

**Comment by MisterGlasses** [comment]
> 还没观察出规律，一张一张抽和5连抽有啥区别？

我试过了 5连抽必中一张高级卡或稀有卡 集成或用万能卡兑换稀有卡要比高级卡划算 高级又比普通划算 建议脚本中可以将万能卡优先兑换为稀有卡或高级卡 普通卡爆率较高 没必要用万能卡换

**Comment by MisterGlasses** [comment]
> 还没观察出规律，一张一张抽和5连抽有啥区别？

普通卡一张值20金币 高级值45 稀有值100

**Comment by Zero-S1** [comment]
是万能卡只用来兑稀有卡，还是也给高级卡凑整？哈

**Comment by MisterGlasses** [comment]
> 是万能卡只用来兑稀有卡，还是也给高级卡凑整？哈

万能卡可以兑换任意一张卡 但兑换普通卡太亏了 现在一天能抽30次奖 每次抽奖大部分中的都是普通卡 很轻松就能集够一套普通卡

**Comment by MisterGlasses** [comment]
> 是万能卡只用来兑稀有卡，还是也给高级卡凑整？哈
 万能卡用来补齐稀有卡或高级卡比较划算

**Comment by Zero-S1** [comment]
> > 是万能卡只用来兑稀有卡，还是也给高级卡凑整？哈
> > 万能卡用来补齐稀有卡或高级卡比较划算

我打算万能卡只凑齐稀有卡，不兑换高级卡凑整了

**Comment by Zero-S1** [comment]
优先5连抽吗

**Comment by MisterGlasses** [comment]
> > > 是万能卡只用来兑稀有卡，还是也给高级卡凑整？哈
> > > 万能卡用来补齐稀有卡或高级卡比较划算
> 
> 我打算万能卡只凑齐稀有卡，不兑换高级卡凑整了

但稀有卡没那么好中 我30连抽也只是中了一张稀有而已

**Comment by MisterGlasses** [comment]
> 优先5连抽吗

连抽爆率高 建议全部连抽

**Comment by MisterGlasses** [comment]
> > > 是万能卡只用来兑稀有卡，还是也给高级卡凑整？哈
> > > 万能卡用来补齐稀有卡或高级卡比较划算
> 
> 我打算万能卡只凑齐稀有卡，不兑换高级卡凑整了

4张万能卡换1张稀有卡 值100金币
4张万能卡换2张高级卡 值90金币
4张万能卡换4张普通卡 值80金币
大佬参考一下吧 可以在差一两张时用万能卡优先补齐稀有卡 其次补齐高级卡 普通卡别浪费万能卡了

**Comment by Zero-S1** [comment]
> > > > 是万能卡只用来兑稀有卡，还是也给高级卡凑整？哈
> > > > 万能卡用来补齐稀有卡或高级卡比较划算
> > 
> > 
> > 我打算万能卡只凑齐稀有卡，不兑换高级卡凑整了
> 
> 4张万能卡换1张稀有卡 值100金币
> 4张万能卡换2张高级卡 值90金币
> 4张万能卡换4张普通卡 值80金币
> 大佬参考一下吧 可以在差一两张时用万能卡优先补齐稀有卡 其次补齐高级卡 普通卡别浪费万能卡了

目前首先5连抽，单个不抽；
然后卡牌兑金币；
最后万能卡只换稀有卡；也不换高级卡
碎片没做

**Comment by MisterGlasses** [comment]
> > > > > 是万能卡只用来兑稀有卡，还是也给高级卡凑整？哈
> > > > > 万能卡用来补齐稀有卡或高级卡比较划算
> > > 
> > > 
> > > 我打算万能卡只凑齐稀有卡，不兑换高级卡凑整了
> > 
> > 
> > 4张万能卡换1张稀有卡 值100金币
> > 4张万能卡换2张高级卡 值90金币
> > 4张万能卡换4张普通卡 值80金币
> > 大佬参考一下吧 可以在差一两张时用万能卡优先补齐稀有卡 其次补齐高级卡 普通卡别浪费万能卡了
> 
> 目前首先5连抽，单个不抽；
> 然后卡牌兑金币；
> 最后万能卡只换稀有卡；也不换高级卡
> 碎片没做

我咋天有30次抽奖机会 今天只有10次抽奖机会 跑跑看看咋样 多谢大佬
