### ISSUE TITLE
脚本运行出错 大佬请看下

### ISSUE THREAD

**Issue by MisterGlasses** [Zero-S1/xmly_speed#19]
代码有点长 请大佬移步看一下 出现很多次了`https://github.com/MisterGlasses/MyActions/runs/1297837728?check_suite_focus=true `
大约在49行

**Comment by Zero-S1** [comment]
网络不稳定造成的，可以忽略

**Comment by MisterGlasses** [comment]
> 网络不稳定造成的，可以忽略

多谢
