### ISSUE TITLE
关于repo-sync问题

### ISSUE THREAD

**Issue by miaomiao2021** [Zero-S1/xmly_speed#29]
[
![Snipaste_2020-11-10_22-08-21](https://user-images.githubusercontent.com/29628114/98684767-87cd0800-23a1-11eb-8c3a-bc132a1821dd.png)
](url)

我自己新建仓库了，打算同步你的仓库了，需要同步yml文件，你帮我改一下，感激！！

**Comment by Zero-S1** [comment]
这并非由我提供，请自行解决
