### ISSUE TITLE
bark提醒 以及设备命名的修改

### ISSUE THREAD

**Issue by qazmcl1230** [Zero-S1/xmly_speed#30]
![5C3BF261-0C78-4AE2-AB0B-D7ECD72252CD](https://user-images.githubusercontent.com/40729710/99183930-8ec99100-277a-11eb-99cc-1b53462eb8d1.jpeg)
这个iPhone7P不是我的设备

**Comment by Zero-S1** [comment]
https://github.com/Zero-S1/xmly_speed/blob/3bc044c6aee623e45aeaf9a6a15e114e317894e7/xmly_speed.py#L24
修改这一行 与账号一一对应

**Comment by qazmcl1230** [comment]
> https://github.com/Zero-S1/xmly_speed/blob/3bc044c6aee623e45aeaf9a6a15e114e317894e7/xmly_speed.py#L24
> 
> 
> 修改这一行 与账号一一对应

我是GitHub action运行的好也要修改吗？

**Comment by Zero-S1** [comment]
当然

**Comment by qazmcl1230** [comment]
> 当然

好的

**Comment by Zero-S1** [comment]
最新版可以自动读取devices了，无需填写
