### ISSUE TITLE
cookie格式是啥，只有我看不到cookie格式的参考图吗

### ISSUE THREAD

**Issue by awei4287** [Zero-S1/xmly_speed#4]
把抓包的全复制进去了，跑起来全是异常终止，感觉我填的cookie格式有问题，参考给的那个png图看不到只是我的问题吗？

**Comment by wy1ng** [comment]
请教下抓cookie的方法，谢谢~~~

**Comment by awei4287** [comment]
我用安卓抓的，弄好软件，用抓包软件（我的是小黄鸟）抓的，然后看包里的cookie
