### ISSUE TITLE
脚本运行出错 大佬请看下

### ISSUE THREAD

**Issue by MaxXue** [Zero-S1/xmly_speed#46]
File "xmly_speed.py", line 944, in run
    answer(cookies)      # 答题赚金币
  File "xmly_speed.py", line 661, in answer
    paperId, _, lastTopicId = ans_start(cookies)
  File "xmly_speed.py", line 260, in ans_start
    paperId = result["data"]["paperId"]
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code 1.

https://github.com/MaxXue/xmly_speed/runs/1412389249?check_suite_focus=true

**Comment by Zero-S1** [comment]
手动答题你试过吗

**Comment by MaxXue** [comment]
大佬，我弄好了
之前我是把抓到的所有Cookie都配了，然后就执行不过。后来把COOKIE内容只要截取到NSUP=xxx之前执行就可以了！不知道为啥
