### ISSUE TITLE
脚本报错

### ISSUE THREAD

**Issue by vaetime** [Zero-S1/xmly_speed#47]
北京时间: 2020-11-17 19:22:35.147122

>>>>>>>【账号开始1】

【刷时长1】
上传本地收听时长1: 1162分钟

【刷时长2】
上传本地收听时长2: 1162分钟

【阅读】

【bubble】
暂无有效气泡

【连续签到】
{'checkId': None, 'historyDays': 1, 'continuousDays': 1, 'isTickedToday': True, 'thatDay': 1, 'broken': False, 'canMakeUp': False, 'newUser': True, 'receivedToday': True}
连续签到1/1天
True

【答题】
时间未到
[看视频回复体力]
{"errorCode":-1,"messageKey":null,"technialMessage":"javax.crypto.BadPaddingException: Decryption error","displayMessage":"generic exception, please contact admin","ret":-1,"data":null,"code":-1,"msg":"generic exception, please contact admin"}
Traceback (most recent call last):
  File "xmly_speed.py", line 976, in <module>
    run()
  File "xmly_speed.py", line 944, in run
    answer(cookies)      # 答题赚金币
  File "xmly_speed.py", line 661, in answer
    paperId, _, lastTopicId = ans_start(cookies)
  File "xmly_speed.py", line 260, in ans_start
    paperId = result["data"]["paperId"]
TypeError: 'NoneType' object is not subscriptable

**Comment by Zero-S1** [comment]
手动答题你试过吗

**Comment by Yaonie-Jie** [comment]
大佬，暂无有效气泡是什么原因 只有18号注册的账号是这样子
