### ISSUE TITLE
行为异常，无法领取金币

### ISSUE THREAD

**Issue by wangmanv2** [Zero-S1/xmly_speed#51]
仓库地址：https://github.com/wangmanv2/hima-alaya
最近刷时长气泡一直提示
```
receive:  {"errorCode":-9995,"messageKey":"-9995","technialMessage":"","displayMessage":"行为异常，无法领取金币","ret":-9995,"data":null,"code":-9995,"msg":"行为异常，无法领取金币"}
{"errorCode":-9995,"messageKey":"-9995","technialMessage":"","displayMessage":"行为异常，无法领取金币","ret":-9995,"data":null,"code":-9995,"msg":"行为异常，无法领取金币"}
```
是什么问题呢？能否手动关闭？

**Comment by Zero-S1** [comment]
我不知道  ，不过你可以尝试： 
先手动完成相关游戏；不行再重新换设备抓包；
再不行放弃就好

**Comment by Zero-S1** [comment]
主要还是需要进入app内手动完成几个对应的项目  气泡和答题都是

**Comment by wangmanv2** [comment]
我之前已经使用了十几天了，都没有任何问题，而且进入app内手动做完任务后，使用脚本领取还是提示`行为异常，无法领取金币`

**Comment by Zero-S1** [comment]
> 刚才重新运行了一下脚本，又没有问题了。
> 
> 昨天两个号同时出现问题，一个号手动操作领取，另外一个号无任何操作，停用脚本12小时后，都正常了。

玄学问题，暂时解决不了
