### ISSUE TITLE
领取万能卡无效参数

### ISSUE THREAD

**Issue by kanvenzeng** [Zero-S1/xmly_speed#59]
【领取万能卡】
{"errorCode":-9999,"messageKey":"-9999","technialMessage":"","displayMessage":"无效参数","ret":-9999,"data":null,"code":-9999,"msg":"无效参数"}

手动领取没有问题，只配置了cookie，其它参数没有配置。

**Comment by Zero-S1** [comment]
没有问题，无效参数是因为当时时间未到，没有领取机会；等待下次运行就好

**Comment by kanvenzeng** [comment]
> 没有问题，无效参数是因为当时时间未到，没有领取机会；等待下次运行就好

每次（30分钟一次）运行都是这样，我打开app是时间到了的，可以领取的。

**Comment by Zero-S1** [comment]
我看自己的运行日志没问题，无法复现你说的问题。等我遇到了再说吧。

**Comment by kanvenzeng** [comment]
> 我看自己的运行日志没问题，无法复现你说的问题。等我遇到了再说吧。

万能卡有这数据：
    data = {
        "listenTime": mins-date_stamp,
        "signData": rsa_encrypt(f"{_datatime}{token}{uid}", pubkey_str),
        "token": token
    }
“mins-date_stamp”这数据在哪里定义？

**Comment by Zero-S1** [comment]
更新到最新脚本试试

**Comment by kanvenzeng** [comment]
> 更新到最新脚本试试

已更新到最新版本

**Comment by kanvenzeng** [comment]
> 更新到最新脚本试试

已更新到最新版本，但还是提示无效参数。
日志：https://github.com/kanvenzeng/myjd1/actions/runs/381226435
cookie：
1&_device=android&dc979c8f-ceae-3b93-b4a5-330dedccbd9d&1.8.42; 1&_token=269006261&06612470340C485D7DEFA6E3D58CE84AFC56F35696C184AE5A1BEC9937867B282DF9A230F78496M9fe43d96CB6DCE6_; channel=and-f6; impl=com.ximalaya.ting.lite; osversion=23; device_model=CAM-AL00; XUM=AFoTqf4l; XIM=3119d411e67fc; c-oper=%E6%9C%AA%E7%9F%A5; net-mode=WIFI; res=720%2C1208; NSUP=; AID=KwTc4EF8eB0=; manufacturer=HUAWEI; umid=77ebf8306bc63df5af3c5073c5b336f6; xm_grade=1000; appVersion=1.8.42.3; yzChannel=and-f6; _xmLog=h5&a80cd72d-27dd-46ad-b684-2b5bfa275102&2.2.5;

**Comment by kanvenzeng** [comment]
> 更新到最新脚本试试

好了，谢谢老大！赞赞赞

**Comment by kanvenzeng** [comment]
> 更新到最新脚本试试

看错了，已更新脚本，但还是提示无效参数。

**Comment by kanvenzeng** [comment]
> 更新到最新脚本试试

日志：https://github.com/kanvenzeng/myjd1/runs/1448161290?check_suite_focus=true
cookie：
1&_device=android&dc979c8f-ceae-3b93-b4a5-330dedccbd9d&1.8.42; 1&_token=269006261&06612470340C485D7DEFA6E3D58CE84AFC56F35696C184AE5A1BEC9937867B282DF9A230F78496M9fe43d96CB6DCE6_; channel=and-f6; impl=com.ximalaya.ting.lite; osversion=23; device_model=CAM-AL00; XUM=AFoTqf4l; XIM=3119d411e67fc; c-oper=%E6%9C%AA%E7%9F%A5; net-mode=WIFI; res=720%2C1208; NSUP=; AID=KwTc4EF8eB0=; manufacturer=HUAWEI; umid=77ebf8306bc63df5af3c5073c5b336f6; xm_grade=1000; appVersion=1.8.42.3; yzChannel=and-f6; _xmLog=h5&a80cd72d-27dd-46ad-b684-2b5bfa275102&2.2.5;

**Comment by Joinmogul** [comment]
更新了，万能卡和card_exchangeCoin 依旧参数错误。
请大佬再解决一下

**Comment by Zero-S1** [comment]
#73 参考
自行解决，不做处理
