### ISSUE TITLE
安卓cookie刷不了时长

### ISSUE THREAD

**Issue by qqeeg** [Zero-S1/xmly_speed#61]
安卓cookie刷不了时长

**Comment by qqeeg** [comment]
ua也按照抓包的改了，但是还是刷不了

**Comment by Zero-S1** [comment]
> 安卓cookie刷不了时长
请掌握基本的提问方法
详细描述：
是否新号
接口的具体返回
是否知道app内需要下拉刷新才能看到 今日收听时长

**Comment by MisterGlasses** [comment]
> 详细描述：
> 是否新号
> 接口的具体返回
> 是否知道app内需要下拉刷新才能看到 今日收听时长
应该不是安卓的问题 我的iOS端账号也无法刷时长
不是新号

接口的具体返回：
`【刷时长1】
上传本地收听时长1: 796分钟
【刷时长2】
上传本地收听时长2: 796分钟 `
`【bubble】
暂无有效气泡 `
万能卡领取跟兑换都是
`{"errorCode":-9999,"messageKey":"-9999","technialMessage":"","displayMessage":"无效参数","ret":-9999,"data":null,"code":-9999,"msg":"无效参数"} `

app内今日收听时长只有几分钟 下拉刷新也无变化 具体请移步action日志
https://github.com/MisterGlasses/xmly_speed/actions

**Comment by hzzhy1987** [comment]
> > 详细描述：
> > 是否新号
> > 接口的具体返回
> > 是否知道app内需要下拉刷新才能看到 今日收听时长
> 
> 应该不是安卓的问题 我的iOS端账号也无法刷时长
> 不是新号
> 
> 接口的具体返回：
> `【刷时长1】 上传本地收听时长1: 796分钟 【刷时长2】 上传本地收听时长2: 796分钟 `
> `【bubble】 暂无有效气泡 `
> 万能卡领取跟兑换都是[#59 (comment)](https://github.com/Zero-S1/xmly_speed/issues/59#issue-748518514)
> `{"errorCode":-9999,"messageKey":"-9999","technialMessage":"","displayMessage":"无效参数","ret":-9999,"data":null,"code":-9999,"msg":"无效参数"} `
> 
> app内今日收听时长只有几分钟 下拉刷新也无变化 具体请移步action日志
> https://github.com/MisterGlasses/xmly_speed/actions

你答题有币吗？

**Comment by MisterGlasses** [comment]
> > > 详细描述：
> > > 是否新号
> > > 接口的具体返回
> > > 是否知道app内需要下拉刷新才能看到 今日收听时长
> > 
> > 
> > 应该不是安卓的问题 我的iOS端账号也无法刷时长
> > 不是新号
> > 接口的具体返回：
> > `【刷时长1】 上传本地收听时长1: 796分钟 【刷时长2】 上传本地收听时长2: 796分钟 `
> > `【bubble】 暂无有效气泡 `
> > 万能卡领取跟兑换都是[#59 (comment)](https://github.com/Zero-S1/xmly_speed/issues/59#issue-748518514)
> > `{"errorCode":-9999,"messageKey":"-9999","technialMessage":"","displayMessage":"无效参数","ret":-9999,"data":null,"code":-9999,"msg":"无效参数"} `
> > app内今日收听时长只有几分钟 下拉刷新也无变化 具体请移步action日志
> > https://github.com/MisterGlasses/xmly_speed/actions
> 
> 你答题有币吗？

有

**Comment by Zero-S1** [comment]
> 应该不是安卓的问题 我的iOS端账号也无法刷时长 相反 另一个安卓号就没问题 App内均可以正常收听并领取金币
> 不是新号
> 
> 接口的具体返回：
> `【刷时长1】 上传本地收听时长1: 796分钟 【刷时长2】 上传本地收听时长2: 796分钟 `
> `【bubble】 暂无有效气泡 `
> 万能卡领取跟兑换都是[#59 (comment)](https://github.com/Zero-S1/xmly_speed/issues/59#issue-748518514)
> `{"errorCode":-9999,"messageKey":"-9999","technialMessage":"","displayMessage":"无效参数","ret":-9999,"data":null,"code":-9999,"msg":"无效参数"} `
> 
> app内今日收听时长只有几分钟 下拉刷新也无变化 具体请移步action日志
> https://github.com/MisterGlasses/xmly_speed/actions
> —————————————
> 最新action日志显示
> 【bubble】
> 2
> receive: {"code":0,"msg":"","data":true}
> {"isValid":false,"coin":null,"totalCoin":62235,"multiple":null}

用最新脚本试试刷时长，加了输出

bubble这个输出 看样子，基础奖励是正常的，但是不能翻倍

无效参数 这个问题我还没遇到过，暂时也不想处理

**Comment by MisterGlasses** [comment]
> > 应该不是安卓的问题 我的iOS端账号也无法刷时长 相反 另一个安卓号就没问题 App内均可以正常收听并领取金币
> > 不是新号
> > 接口的具体返回：
> > `【刷时长1】 上传本地收听时长1: 796分钟 【刷时长2】 上传本地收听时长2: 796分钟 `
> > `【bubble】 暂无有效气泡 `
> > 万能卡领取跟兑换都是[#59 (comment)](https://github.com/Zero-S1/xmly_speed/issues/59#issue-748518514)
> > `{"errorCode":-9999,"messageKey":"-9999","technialMessage":"","displayMessage":"无效参数","ret":-9999,"data":null,"code":-9999,"msg":"无效参数"} `
> > app内今日收听时长只有几分钟 下拉刷新也无变化 具体请移步action日志
> > https://github.com/MisterGlasses/xmly_speed/actions
> > —————————————
> > 最新action日志显示
> > 【bubble】
> > 2
> > receive: {"code":0,"msg":"","data":true}
> > {"isValid":false,"coin":null,"totalCoin":62235,"multiple":null}
> 
> 用最新脚本试试刷时长，加了输出
> 
> bubble这个输出 看样子，基础奖励是正常的，但是不能翻倍
> 
> 无效参数 这个问题我还没遇到过，暂时也不想处理

报错

Traceback (most recent call last):
  File "xmly_speed.py", line 1036, in <module>
    run()
  File "xmly_speed.py", line 996, inrun
    saveListenTime(cookies, date_stamp)
  File "xmly_speed.py", line 736, in saveListenTime
    print(response.text)
NameError: name 'response' is not defined
Error: Process completed with exit code 1.

**Comment by Zero-S1** [comment]
> > 用最新脚本试试刷时长，加了输出
> > bubble这个输出 看样子，基础奖励是正常的，但是不能翻倍
> > 无效参数 这个问题我还没遇到过，暂时也不想处理
> 
> 报错
> 
> Traceback (most recent call last):
> File "xmly_speed.py", line 1036, in
> run()
> File "xmly_speed.py", line 996, inrun
> saveListenTime(cookies, date_stamp)
> File "xmly_speed.py", line 736, in saveListenTime
> print(response.text)
> NameError: name 'response' is not defined
> Error: Process completed with exit code 1.

刚才代码有误，可以再试一次最新的代码

**Comment by MisterGlasses** [comment]
> > > 用最新脚本试试刷时长，加了输出
> > > bubble这个输出 看样子，基础奖励是正常的，但是不能翻倍
> > > 无效参数 这个问题我还没遇到过，暂时也不想处理
> > 
> > 
> > 报错
> > Traceback (most recent call last):
> > File "xmly_speed.py", line 1036, in
> > run()
> > File "xmly_speed.py", line 996, inrun
> > saveListenTime(cookies, date_stamp)
> > File "xmly_speed.py", line 736, in saveListenTime
> > print(response.text)
> > NameError: name 'response' is not defined
> > Error: Process completed with exit code 1.
> 
> 刚才代码有误，可以再试一次最新的代码

日志内容挺多 大佬看下
https://github.com/MisterGlasses/xmly_speed/runs/1446394799?check_suite_focus=true

**Comment by Zero-S1** [comment]
> 日志内容挺多 签名错误 大佬看下
> https://github.com/MisterGlasses/xmly_speed/runs/1446394799?check_suite_focus=true

我看了一下你的日志，发现几乎没有能够正常运行的，你试着重新抓取cookie信息试试

**Comment by MisterGlasses** [comment]
> > 日志内容挺多 签名错误 大佬看下
> > https://github.com/MisterGlasses/xmly_speed/runs/1446394799?check_suite_focus=true
> 
> 我看了一下你的日志，发现几乎没有能够正常运行的，你试着重新抓取cookie信息试试 @MisterGlasses

现在的日志就是重抓的 这个跟App版本有没有关系

**Comment by Zero-S1** [comment]
> 现在的日志就是重抓的 这个跟App版本有没有关系

那你把cookie发我，让我测试一下看看

**Comment by MisterGlasses** [comment]
> > 现在的日志就是重抓的 这个跟App版本有没有关系
> 
> 那你把cookie发我，让我测试一下看看

怎么私发😂

**Comment by Zero-S1** [comment]
直接发吧，其实没啥隐私信息，待会我把评论删掉就行

**Comment by MisterGlasses** [comment]
> 直接发吧，其实没啥隐私信息，待会我把评论删掉就行

`1&_device=iPhone&A4A3A8D1-0EBF-4710-A01F-108DA1B63C77&1.1.13; XUM=A4A3A8D1-0EBF-4710-A01F-108DA1B63C77; idfa=00000000-0000-0000-0000-000000000000; device_model=iPhone XR; c-oper=%E6%9C%AA%E7%9F%A5; net-mode=4G; ip=10.32.190.236; res=828%2C1792; NSUP=; ainr=0; XD=RW0cXx4O8RaA+dS6sCSTpd940EW0sb7knqWMI+aFdkk+zMCJeCH2oA40CtnFdRwG/YpkP4nWzYOEWdQhnmKOGg==; 1&_token=258722083&330C1990340CEB5BD86AC66BE679A5558E36888CD23AB7BF101849C4AD9DAC0E560253FC22FC139MA1F00D771B1636F_ `

**Comment by Zero-S1** [comment]
> 怎么私发😂
你加一下QQ吧 861569352，方便交流

**Comment by Zero-S1** [comment]
- [x] 无法刷时长的问题和无效参数基本已经解决，更新最新代码即可
- [ ] 账号异常暂时无法解决

**Comment by hzzhy1987** [comment]
> * [x]  无法刷时长的问题和无效参数基本已经解决，更新最新代码即可
> * [ ]  账号异常暂时无法解决
安卓抓的cookie，时长没问题了，抽卡参数还是有问题，日志：
https://github.com/hzzhy1987/xmlyspeed/runs/1447742761

**Comment by Zero-S1** [comment]
> >   安卓抓的cookie，时长没问题了，抽卡参数还是有问题，日志：
> >   https://github.com/hzzhy1987/xmlyspeed/runs/1447742761

你也加我qq吧 861569352

**Comment by 1260074755** [comment]
> > > 安卓抓的cookie，时长没问题了，抽卡参数还是有问题，日志：
> > > https://github.com/hzzhy1987/xmlyspeed/runs/1447742761
> 
> 你也加我qq吧 861569352

大佬，我也是这个问题。已经同步大佬你的脚本了，但是还是无法刷时长，还提示“验证签名错误”

**Comment by 1260074755** [comment]
> > > > 安卓抓的cookie，时长没问题了，抽卡参数还是有问题，日志：
> > > > https://github.com/hzzhy1987/xmlyspeed/runs/1447742761
> 
> 大佬，我也是这个问题。已经同步大佬你的脚本了，但是还是无法刷时长，还提示“验证签名错误”

感谢大佬，已经好了！

**Comment by Zero-S1** [comment]
请实际更新到最新脚本，运行后有问题再来提问。
