### ISSUE TITLE
通过脚本同步方式 同步失败

### ISSUE THREAD

**Issue by cksspk** [Zero-S1/xmly_speed#65]
![image](https://user-images.githubusercontent.com/37790595/100059730-7f2b0600-2e66-11eb-8d67-b57daf813b22.png)
每一个步骤都是按照教程进行
但是触发同步的时候，出现了错误
![image](https://user-images.githubusercontent.com/37790595/100059799-9f5ac500-2e66-11eb-8511-d6e507f9948e.png)
这是为什么？？如何解决

**Comment by Zero-S1** [comment]
不做回答，请咨询 @AboutCXJ 
[相关commit](https://github.com/Zero-S1/xmly_speed/commit/1cf83e92cd9b0d0200ed334ec25771b1abeec6a2)

**Comment by chehongbin** [comment]
我也是按照这个设置的， 直接star  测试 action， 运行 提示 skip. PAT 也配置了
