### ISSUE TITLE
[BUG]安卓版cookie无法正常答题/抽卡/获取气泡，切换回iPhone版cookie就正常。

### ISSUE THREAD

**Issue by qqeeg** [Zero-S1/xmly_speed#73]
## 1. 关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种运行方案

- [x] 方法一：GitHub action自动运行 
- [ ] 方法二：本地运行

### (1) 具体问题
A：安卓版cookie无法正常答题/抽卡/获取气泡，切换回iPhone版cookie就正常。

### (2) 详细日志(如果是GitHub action运行，请附上具体网址)
A：安卓cookie的日志：https://github.com/qqeeg/xmly_bak/runs/1449436509?check_suite_focus=true
      苹果cookie的日志：https://github.com/qqeeg/xmly_bak/runs/1449455170?check_suite_focus=true

**Comment by Zero-S1** [comment]
那挺好的，答案就在题目中。

**Comment by Joinmogul** [comment]
自测和设备没关系 安卓换回老ck能用了。新ck参数错误

**Comment by Zero-S1** [comment]
抽卡参数无效 与 无法获取气泡/行为异常 属于两个问题。  行为异常无解 ，参数无效可能与安卓有关，待测

**Comment by hzzhy1987** [comment]
> 自测和设备没关系 安卓换回老ck能用了。新ck参数错误

老ck怎么获得

**Comment by hootigger** [comment]
已测试,发现无效.抓包ck就是iPhone的1.1.13版本.且UA也替换了抓包抓到的.依然 万能卡无效参数.  上传时长:{"msg":"验证签名错误","ret":3}

**Comment by qqeeg** [comment]
> 自测和设备没关系 安卓换回老ck能用了。新ck参数错误



> 自测和设备没关系 安卓换回老ck能用了。新ck参数错误

旧版本app能辅否抓到老ck呢

**Comment by qqeeg** [comment]
> 自测和设备没关系 安卓换回老ck能用了。新ck参数错误

还有就是方便发一下老ck的格式吗，你把token去掉就行了，我看看用新ck改成老ck的格式行不行

**Comment by kanvenzeng** [comment]
用旧版的app抓cookie后，其它都正常了，万能卡不再提示无效参数了，变成提示“行为异常，无法领取金币”。是黑号了吗？
日志：https://github.com/kanvenzeng/myjd1/runs/1451777000?check_suite_focus=true

**Comment by Joinmogul** [comment]
楼上的请问旧版是哪个版本号？ 这办法不错

**Comment by Joinmogul** [comment]
> 用旧版的app抓cookie后，其它都正常了，万能卡不再提示无效参数了，变成提示“行为异常，无法领取金币”。是黑号了吗？
> 日志：https://github.com/kanvenzeng/myjd1/runs/1451777000?check_suite_focus=true

请问是哪个版本号

**Comment by 78008495** [comment]
直接修改版本号，新版本cookie把18.42.3改成18.39.3，改2处，具体自己找，亲测可用

**Comment by kanvenzeng** [comment]
> 成18.39.3



> > 用旧版的app抓cookie后，其它都正常了，万能卡不再提示无效参数了，变成提示“行为异常，无法领取金币”。是黑号了吗？
> > 日志：https://github.com/kanvenzeng/myjd1/runs/1451777000?check_suite_focus=true
> 
> 请问是哪个版本号

15.3.3
