### ISSUE TITLE
可以在cookie失效通知一下吗？

### ISSUE THREAD

**Issue by MisterGlasses** [Zero-S1/xmly_speed#8]
大佬可以在cookie失效通过server或bark通知一下吗？像lxk大佬的京东脚本那样。

**Comment by Zero-S1** [comment]
不加 ，我玩了2个月，cookie不过期

**Comment by MisterGlasses** [comment]
> 不加 ，我玩了2个月，cookie不过期

这么爽嘛 打扰了打扰了

**Comment by ak6102** [comment]
小白问个问题，怎么从喜马拉雅app里面抓cookie啊

**Comment by MisterGlasses** [comment]
> 小白问个问题，怎么从喜马拉雅app里面抓cookie啊

用抓包工具诸如qx小黄鸟这类的抓
