### ISSUE TITLE
[BUG]阅读没有内容

### ISSUE THREAD

**Issue by x1iu** [Zero-S1/xmly_speed#80]
## 1. 关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种运行方案

- [x] 方法一：GitHub action自动运行 
- [ ] 方法二：本地运行

### (1) 具体问题
A：
![image](https://user-images.githubusercontent.com/44594408/100370518-5e6ad800-3041-11eb-93e5-2d3dd42440ba.png)
阅读没有内容，其他好像都正常。

### (2) 详细日志(如果是GitHub action运行，请附上具体网址)
A：https://github.com/x1iu/xmly/runs/1459728884?check_suite_focus=true

**Comment by Zero-S1** [comment]
不是bug，iOS没有此活动
