### ISSUE TITLE
征集一个新注册的账号便于测试

### ISSUE THREAD

**Issue by Zero-S1** [Zero-S1/xmly_speed#81]
如果你是新注册的xmly账号，欢迎留言联系

**Comment by Aaron-lv** [comment]
我这里有个新注册的号，脚本更新到最新了，一加手机抓的cookie。基本只能开宝箱。1&_device=android&f2494f57-4bd7-373d-a13d-c4b8755b6996&1.8.42;1&_token=269869598&AC892AF0140C7A6332363859F293BF4AE97A825159A54F8D0727B8447BFAC4075541C4D9B805173M4771489F91E0CD2_;channel=and-d8;impl=com.ximalaya.ting.lite;osversion=29;device_model=ONEPLUS+A5010;XUM=lGUtN4pn;XIM=;c-oper=%E4%B8%AD%E5%9B%BD%E8%81%94%E9%80%9A;net-mode=WIFI;res=1080%2C2016;NSUP=;AID=lsIZTH45LXk=;manufacturer=OnePlus;XD=uirmkHsXwI3X9WP1jTzquo65Wxh9gueJwCsIBTf1lg9RDHd9qH9bjZNxM2MqDxPOtXIhBCI6rltfph10QW8gJ5K1IFuZusDj6pe6HLALk0CLo88KQrPONWXHQ4gnYc0anoQMAGIU95Nlwx5v1z7QQA==;umid=5fe2f6e6fe001cbf4941e864b1dbfca0od;xm_grade=1000;oaid=E940C02A0A11689FD3F88C6A86C8A09FD0EAB195B390EA6F9B65F8A240A68F15;appVersion=1.8.42.3;x-abtest-bucketIds=204899;domain=.ximalaya.com;path=/;

**Comment by TWOBUG31** [comment]
有一个注册4天左右的号

**Comment by Zero-S1** [comment]
> 有一个注册4天左右的号

需要三天以内的哈

**Comment by lplbb** [comment]
我可以申请一个
