### ISSUE TITLE
Error: Process completed with exit code 1.

### ISSUE THREAD

**Issue by pingshu** [Zero-S1/xmly_speed#9]
![QQ图片20200930173811](https://user-images.githubusercontent.com/22138807/94669535-f307d100-0343-11eb-8fe8-73887040eb2c.png)

**Comment by Zero-S1** [comment]
给网址

**Comment by pingshu** [comment]
https://github.com/pingshu/xmly_speed/actions

**Comment by Zero-S1** [comment]
明显有账号cookie填错了

**Comment by pingshu** [comment]
就1个账号，而且
![QQ图片20200930203812](https://user-images.githubusercontent.com/22138807/94686115-f491c300-035c-11eb-8a12-466065d364d8.png)

这样填的，对吗

**Comment by Zero-S1** [comment]
看样子是对的 ，你最后换行了吗 ，把最后的回车键去掉  光标留在字符串最后，不要另起一行

**Comment by pingshu** [comment]
好了，谢谢，可能和“回车键另起一行”有关

**Comment by Zero-S1** [comment]
感谢反馈  已提交更新
