### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Arrogance-H** [Zero-S1/xmly_speed#90]
## 1. 关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种运行方案

- [x] 方法一：GitHub action自动运行 
- [ ] 方法二：本地运行

### (1) 具体问题
A：只填写了一个cookie账号，报第二个账号cookie错误

### (2) 详细日志(如果是GitHub action运行，请附上具体网址)
A：https://github.com/Arrogance-H/xmly-iPhone/runs/1542005561?check_suite_focus=true

**Comment by Arrogance-H** [comment]
https://github.com/Arrogance-H/xmly-iPad/runs/1542007704?check_suite_focus=true

**Comment by Zero-S1** [comment]
说明填错了呗  可能换行了

**Comment by Hello-XPH** [comment]
@Zero-S1 
![image](https://user-images.githubusercontent.com/56664327/102045674-954c3680-3e14-11eb-8a3c-82e107b26e80.png)

**Comment by Zero-S1** [comment]
不作解决
